learnsession/urls.py
from django.urls import path
from . import views

app_name = 'learnsession'

urlpatterns = [
    path('', views.index, name='index'),
    path("login/", views.my_view, name='my_view'),
    path("sukses/", views.sukseslogin, name='sukseslogin'),
    path("logout/", views.sukseslogout, name='sukseslogout')
    # dilanjutkan ...
]

story9/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learnsession.urls')),
]

learnsession/models.py
from django.db import models

# Create your models here.

learnsession/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout

def index(request):
	return render(request,'index.html')

def my_view(request):
	username = request.POST['username']
	password = request.POST['password']
	user = authenticate(request, username=username, password=password)
	if user is not None:
		login(request, user)
		request.session['my_session'] = username
		return redirect("learnsession:sukseslogin")
	else:
		gagal = "Password/Username salah!"
		return render(request,'index.html', {"gagal":gagal})

def sukseslogin(request):
	if request.session.get('my_session') is not None:
		value = request.session['my_session']
	return render(request, 'login.html', {"nama": value})

def sukseslogout(request):
	logout(request)
	return redirect("learnsession:index")

  

# Create your views here.

learnsession/templates/index.html
{% load static %}

<!doctype html>
<html lang="en">
	<head>
		<title>Hi There!</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<link rel="stylesheet" href="{% static 'css/gayain.css' %}">
	</head>
	<body>
		<div class="container">
			<div class="jumbotron jumbotron-fluid judul">
  				<div class="container pesan">
			    	<h1 class="display-4">Log In</h1>
				</div>
			</div>

	    	<form autocomplete="off" id="form" action="/login/" method="POST">
	    		{% csrf_token %}	
	    		<h2> {{gagal}} </h2>
				<div class="form-group">
					<label for="username">Username</label>
			    	<input type="text" id="username" class="form-control" placeholder="Enter username" name="username">
				</div>
				<div class="form-group">
			    	<label for="exampleInputPassword1">Password</label>
			    	<input type="password" class="form-control" id="password" placeholder="Enter password" name="password">
			  	</div>
			  	<button type="submit" class="btn btn-primary">Submit</button>
			</form>
			
		</div>
	</body>
</html>

learnsession/templates/login.html
{% load static %}

<!doctype html>
<html lang="en">
	<head>
		<title>Login!</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<link rel="stylesheet" href="{% static 'css/gayain.css' %}">
	</head>
	<body>
		<div class="container">
			<div class="jumbotron jumbotron-fluid judul">
  				<div class="container pesan">
			    	<h1 class="display-4">Welcome</h1>
				</div>
			</div>
		<!-- <form autocomplete="off" id="form" action="/login/" method="POST">
			{% csrf_token %}		
        	<input type="text" id="username" class="form-control form-control-lg" placeholder="Username" name="username">
        	<input type="password" id="password" class="form-control form-control-lg" placeholder="Password" name="password">
        	<button type="submit" class="btn btn-block btn-lg btn-primary button">Login!</button>
    	</form> -->

	    	<h2> Hello {{nama}}! You've been login. </h2>
	    	<br>
	    	<a href="{% url 'learnsession:sukseslogout' %}" class="btn btn-primary">Log Out</a>
		</div>

	</body>
</html>